main: me.desmondcchi.mythical_powers.Main
name: MythicalPowers
author: desmondcchi
version: 0.0.1
commands:
   lightning:
      usage: /lightning
      description: Strike lightning!
   fireball:
      usage: /fireball
      description: Shoot fireball! (/fireball <POWER> <VELOCITY> for custom explosion power and velocity)